### ISSUE TITLE
Training for Word-Vector model taking much time. 

### ISSUE THREAD

**Issue by prakhar21** [salestock/fastText.py#53] opened 2016-08-25 11:40 UTC
hi,
I am trying to use fasttext python package. I am trying to train my word-vector model using the below command.
`model = fasttext.skipgram('path-to-data', 'model')`
It has been like 30 minutes, and it is still training or is hung, I don't know.
My file contains just 2 statements on different lines.

Thanks

**Comment by pyk** [comment] 2016-08-25 12:00
Hi @prakhar21 ,

Which version of fasttext are you currently using? 

```
pip list | grep fasttext
```

The problem that you are described here is related with #49, we have a problem with `v0.7.1` release and it is fixed on `v0.7.2` release.

**Comment by prakhar21** [comment] 2016-08-25 12:04
Hi @pyk , I am using `v0.7.2` only.

**Comment by pyk** [comment] 2016-08-25 12:11
Thanks!

We can reproduce your case using the following simple data:

```shell
% cat data.txt 
simple
statement
% python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasttext
>>> model = fasttext.skipgram('data.txt', 'model')
^C^CKilled
```

Hotfix is on progress

**Comment by pyk** [comment] 2016-08-25 12:40
Hi @prakhar21, turns out that this is also happen in `fasttex(1)`, already reported here https://github.com/facebookresearch/fastText/issues/63

For now please use:

```
model = fasttext.skipgram('small_data.txt', 'model', min_count=1)
```

**Closed by pyk** 2016-08-25 12:40 UTC
Labels: bug

**Comment by prakhar21** [comment] 2016-08-25 12:50
@pyk Okay Thanks.
